### ISSUE TITLE
Not working for labels with more than one object

### ISSUE THREAD

**Issue by pooya-mohammadi** [alimoradynezhad/Change-file-text-with-Python#4]
When there are two or more than two objects in a label file the code just processes the first line and ignores the rest. On top of that, the code removes the rest of the labels from the label file.
@Zzamani80 
@Fereshteh8a
@alimoradynezhad

**Comment by alimoradynezhad** [comment]
Code problem solved
used  f.read()  for read all line of file 
Get the number of lines of a file using    len(f.readlines())

**Comment by alimoradynezhad** [comment]
[Solve the problem Not working for labels with more than one object](https://github.com/alimoradynezhad/Change-file-text-with-Python/commit/0d0019d29b9c7568a0aabe5210b36f612030376f) https://github.com/alimoradynezhad/Change-file-text-with-Python/issues/4

**Comment by alimoradynezhad** [comment]
Code problem solved
used f.read() for read all line of file
Get the number of lines of a file using len(f.readlines())

[Solve the problem Not working for labels with more than one object](https://github.com/alimoradynezhad/Change-file-text-with-Python/commit/0d0019d29b9c7568a0aabe5210b36f612030376f) https://github.com/alimoradynezhad/Change-file-text-with-Python/issues/4
